# SPDX-FileCopyrightText: Â© 2022 Society of Research Software Engineering <info@society-rse.org>
# SPDX-License-Identifier: CC0-1.0

[stfc_daresbury_laboratory]
name = "STFC Computational Science and Engineering Division"
head = "Ilian Todorov"
website = "https://www.scd.stfc.ac.uk/Pages/Computational-Chemistry-Group.aspx"
email = "ilian.todorov@stfc.ac.uk"
phone = "01925603681"
twitter = "@ilian_t_todorov"
postcode = "WA4 4AD"
lat = 53.3446
lon = -2.6400

[ati]
name = "Alan Turing Institute"
head = "Martin O'Reilly"
website = "https://www.turing.ac.uk/research-engineering"
email = "moreilly@turing.ac.uk"
phone = "020 3862 3359"
twitter = "@turinghut23"
postcode = "NW1 2DB"
lat = 51.529985
lon = -0.127014

[ukaea]
name = "UKAEA"
head = "Dan Short"
website = "No external website but https://twitter.com/RSECulham"
email = "dan.short@ukaea.uk"
phone = "01235 467737"
twitter = "@RSECulham"
postcode = "OX14 3EB"
lat = 51.658881
lon = -1.227663

[bas]
name = "British Antarctic Survey Digital Innovation Team"
head = "James Byrne"
website = "https://www.bas.ac.uk"
email = "digitalinnovation@bas.ac.uk"
postcode = "CB3 0ET"
lat = 52.212674
lon = 0.080192

[bath]
name = "University of Bath"
head = "Georgie Wellock"
website = "FWIW: https://www.bath.ac.uk/campaigns/research-software-engineering/"
email = "rse-support@bath.ac.uk / glw33@bath.ac.uk"
postcode = "BA2 7AY"
lat = 51.379324
lon = -2.327157

[birmingham]
name = "University of Birmingham"
head = "Andrew Edmondson"
website = "https://intranet.birmingham.ac.uk/it/teams/infrastructure/research/bear/rsg/research-software-group.aspx"
postcode = "B15 2TT"
lat = 52.453282
lon = -1.92789

[bristol]
name = "University of Bristol"
head = "Christopher Woods"
website = "No good external website, but https://www.bristol.ac.uk/acrc/research-software-engineering/"
email = "ask-rse@bristol.ac.uk"
phone = "No phone number (21C email, slack, twitter only)"
twitter = "@BristolRSE"
postcode = "BS8 1TH"
lat = 51.459066
lon = -2.603291

[bristol-rit]
name = "University of Bristol"
head = "Serena Cooper"
website = "https://www.bristol.ac.uk/research-it/"
email = "research-it@bristol.ac.uk"
twitter = "@BrisUniRIT"
postcode = "BS1 5QD"
lat = 51.452834
lon = -2.605137

[cambridge]
name = "University of Cambridge"
head = "Chris Edsall"
website = "rse.group.cam.ac.uk"
email = "cje57@cam.ac.uk"
twitter = "@RSECambridge"
postcode = "CB2 1TN"
lat = 52.205105
lon = 0.116179

[cardiff]
name = "University of Cardiff"
postcode = "CF10 3AT"
lat = 51.489014
lon = -3.179717

[durham]
name = "Durham University"
head = "Ed Ruck-Keene"
website = "https://www.dur.ac.uk/arc/rse"
email = "arc@durham.ac.uk"
twitter = "@ARC_DU"
postcode = "DH1 3LE"
lat = 54.768112
lon = -1.571874

[epcc]
name = "EPCC"
head = "Lorna Smith/Andy Turner"
website = "http://www.epcc.ed.ac.uk"
email = "info@epcc.ed.ac.uk"
phone = "0131 650 5030"
postcode = "EH8 9BT"
lat = 55.94527
lon = -3.186426

[francis-crick-institute]
name = "Francis Crick Institute"
postcode = "NW1 1AT"
lat = 51.531854
lon = -0.128033

[glasgow-mvls]
name = "College of Medical, Veterinary & Life Sciences; University of Glasgow"
head = "Iain Barrass"
email = "iain.barrass@glasgow.ac.uk"
postcode = "G12 8QB"
lat = 55.8739
lon = -4.2880

[imperial-college-london]
name = "Imperial College London"
website = "https://www.imperial.ac.uk/admin-services/ict/self-service/research-support/rcs/research-software-engineering/"
email = "rse-team-lead@imperial.ac.uk"
postcode = "SW7 2AZ"
lat = 51.498317
lon = -0.176923

[imperial-college-london-reside]
name = "RESIDE"
head = "Rich FitzJohn"
website = "https://reside-ic.github.io/"
email = "reside@imperial.ac.uk"
postcode = "W2 1NY"
lat = 51.5170
lon = 0.1735

[kings-college-london]
name = "King's College London"
head = "James Graham"
website = "https://docs.er.kcl.ac.uk/"
email = "e-research@kcl.ac.uk"
postcode = "SE1 0NZ"
lat = 51.505292
lon = -0.100202

[kings-digital-lab]
name = "King's Digital Lab"
head = "Arianna Ciula"
website = "https://kdl.kcl.ac.uk/"
email = "kdl-info@kcl.ac.uk"
postcode = "WC2B 6LE"
lat = 51.514787
lon = -0.118018

[leeds]
name = "University of Leeds"
head = "Martin Callaghan"
website = "https://arc.leeds.ac.uk"
email = "m.callaghan@leeds.ac.uk"
postcode = "LS2 9JT"
lat = 53.807958
lon = -1.553329

[leicester]
name = "University of Leicester"
postcode = "LE1 7RH"
lat = 52.622086
lon = -1.124531

[manchester]
name = "The University of Manchester"
head = "Robert Haines"
website = "http://www.itservices.manchester.ac.uk/research/"
email = "robert.haines@manchester.ac.uk"
phone = "0161 275 7821"
postcode = "M13 9PL"
lat = 53.466926
lon = -2.233578

[newcastle]
name = "Newcastle University"
head = "Mark Turner"
email = "mark.turner@ncl.ac.uk"
postcode = "NE1 7RU"
lat = 54.98032
lon = -1.615713

[nottingham]
name = "University of Nottingham"
head = "Philip Quinlan"
email = "Philip.Quinlan@nottingham.ac.uk"
postcode = "NG7 2RD"
lat = 52.940521
lon = -1.191193

[open-university]
name = "Open University"
head = "Michelle Bachler"
email = "Michelle Bachler"
phone = "01908 659836"
postcode = "MK7 6AA"
lat = 52.024914
lon = -0.709747

[oxford]
name = "University of Oxford"
head = "Martin Robinson"
website = "https://www.rse.ox.ac.uk/"
email = "rse@cs.ox.ac.uk"
phone = "01865 610671"
postcode = "OX1 3QD"
lat = 51.759895
lon = -1.258503

[queen-mary-university-of-london]
name = "Queen Mary University of London"
head = "(vacant)"
email = "its-research-rse@qmul.ac.uk"
postcode = "E1 4NS"
lat = 51.524636
lon = -0.04071

[reading]
name = "University of Reading"
head = "Paul Heaton & Maria Broadbridge"
website = "https://research.reading.ac.uk/rse/"
email = "p.m.heaton@reading.ac.uk; m.b.broadbridge@reading.ac.uk"
postcode = "RG6 6AH"
lat = 51.457625
lon = -0.945636

[sheffield]
name = "The University of Sheffield"
head = "Romain Thomas"
website = "http://rse.shef.ac.uk"
email = "rse@sheffield.ac.uk"
twitter = "RSE_Sheffield"
postcode = "S10 2TN"
lat = 53.381363
lon = -1.48853

[southampton]
name = "University of Southampton"
head = "Simon Hettrick and John Robinson"
website = "https://rsgsoton.net/"
email = "rsg-info@soton.ac.uk"
phone = "02380 595729"
twitter = "@RSGSoton"
postcode = "SO17 1BJ"
lat = 50.934099
lon = -1.395714

[st-andrews]
name = "University of St Andrews"
head = "Olexandr Konovalov"
website = "https://rse.cs.st-andrews.ac.uk/"
email = "obk1@st-andrews.ac.uk"
phone = "01334 461633"
postcode = "KY16 9SX"
lat = 56.339949
lon = -2.809421

[st-andrews-rescomp]
name = "University of St Andrews"
head = "Patrick McCann/Swithun Crowe/ Mary Woodcock Kroble"
website = "(slightly out-of-date; new site expected soon) https://www.st-andrews.ac.uk/library/services/researchsupport/digihum-rescomp/"
email = "research-computing@st-andrews.ac.uk"
postcode = "KY16 9AL"
lat = 56.341752
lon = -2.793303

[stfc-software-engineering-group]
name = "STFC Software Engineering Group"
head = "Alejandra Gonzalez-Beltran"
website = "https://www.scd.stfc.ac.uk/Pages/Software-Engineering-Group.aspx"
email = "alejandra.gonzalez-beltran@stfc.ac.uk"
phone = "+44 (0)1235 446339"
postcode = "OX11 0QX"
lat = 51.574887
lon = -1.314517

[strathclyde]
name = "University of Strathclyde"
head = "Oliver Henrich"
email = "oliver.henrich@strath.ac.uk"
phone = "0141 548 4012"
postcode = "G4 0NG"
lat = 55.861521
lon = -4.239865

[swansea]
name = "Swansea Academy of Advanced Computing, Swansea University"
head = "Ed Bennett/Mark Dawson"
website = "No external website but https://twitter.com/sa2c_swansea"
email = "e.j.bennett@swansea.ac.uk/mark.dawson@swansea.ac.uk"
phone = "01792 513617"
postcode = "SA1 8EN"
lat = 51.6188
lon = -3.879405

[university-college-london]
name = "University College London"
head = "Jonathan Cooper"
website = "https://www.ucl.ac.uk/advanced-research-computing/research-software-engineers"
email = "arc.collaborations@ucl.ac.uk"
phone = "020 310 86297"
postcode = "WC1E 6BT"
lat = 51.523569
lon = -0.132424

[university-college-london-neuroinformatics]
name = "Neuroinformatics Unit"
head = "Adam Tyson"
email = "adam.tyson@ucl.ac.uk"
postcode = "W1T 4JG"
lat = 51.521118
lon = -0.138367

[york]
name = "University of York"
head = "Emma Barnes, Philip Harrison"
website = "https://www.york.ac.uk/it-services/research-computing/research-software-engineers/"
email = "itsupport@york.ac.uk"
postcode = "YO10 5DD"
lat = 53.948419
lon = -1.053544

[exeter]
name = "University of Exeter"
head = "Katie Finch"
website = "https://www.exeter.ac.uk/idsai/team/researchsoftwareengineers/"
email = "k.j.finch@exeter.ac.uk"
postcode = "EX4 4PY"
lat = 50.735424
lon = -3.534504

[Rosalind_Franklin_Institute]
name = "Rosalind Franklin Institute"
head = "Mark Basham"
website = "https://www.rfi.ac.uk/research/artificial-intelligence/"
email = "mark.basham@rfi.ac.uk"
twitter = "@basham_mark"
postcode = "OX11 0QX"
lat = 51.573541227928786
lon = -1.314570656497308

[RSE-NI]
name = "Queen's University Belfast"
head = "Domhnall Carlin, Andrew Brown"
website = "https://rse-ni.github.io/"
email = "d.carlin@qub.ac.uk, a.brown@qub.ac.uk"
phone = ""
twitter = ""
postcode = "BT7 1NN"
lat = 54.584558
lon = -5.935766

[Gottingen_State_and_University_Library]
name = "Software and Service Development Group, Gottingen State and University Library"
website = "https://www.sub.uni-goettingen.de/en/contact/departments-a-z/departmental-and-unit-details/abteilunggruppe/software-und-service-entwicklung/"
lat = 51.53953
lon = 9.93603

[netherlands_escience]
name = "Netherlands eScience Center"
website = "https://www.esciencecenter.nl"
lat = 52.35674
lon = 4.95688

[cape_town]
name = "eResearch and Computational Biology Division (developers employed by the Division), University of Cape Town"
website = "http://www.cbio.uct.ac.za/"
lat = -33.95756
lon = 18.46118

[western_cape]
name = "South African National Bioinformatics Institute (developers/devops employed by the Institute), University of the Western Cape"
website = "https://www.uwc.ac.za/study/all-areas-of-study/institutes/south-african-national-bioinformatics-institute/overview"
lat = -33.93349
lon = 18.62799

[National_Bioinformatics_Infrastructure_Sweden]
name = "National Bioinformatics Infrastructure Sweden"
website = "https://nbis.se/"
lat = 59.35047
lon = 18.02344

[argonne_petsc]
name = "PETSc Team, Argonne National Laboratory"
website = "https://www.anl.gov/mcs/petsc-portable-extensible-toolkit-for-scientific-computation"
lat = 41.71833
lon = -87.97887

[indiana_d2i_pti]
name = "Data to Insight Center (D2I) and Pervasive Technology Institute (PTI), Indiana University"
website = "https://pti.iu.edu/centers/d2i/people.html"
lat = 39.17328
lon = -86.51894

[louisiana_state_cct_hpc]
name = "HPC enablement group, Center for Computation and Technology, Louisiana State University"
website = "https://www.cct.lsu.edu/programs/hpc-enablement"
lat = 30.40993
lon = -91.18003

[nsca_illinois]
name = "National Center for Supercomputing Applications (NCSA), University of Illinois Urbana-Champaign"
website = "https://www.ncsa.illinois.edu/"
lat = 40.11492
lon = -88.22488

[renci]
name = "Renaissance Computing Institute (RENCI)"
website = "https://renci.org/"
lat = 35.939561
lon = -79.018753

[arcs_viginia]
name = "Research Computing, University of Virginia"
website = "https://www.rc.virginia.edu"
lat = 38.03345
lon = -78.50793

[princeton]
name = "Princeton Research Computing"
website = "https://researchcomputing.princeton.edu"
lat = 40.34616
lon = -74.65267

[nocl]
name = "National Oceanography Centre - Liverpool"
lat = 53.4074492
lon = -2.9716602
postcode = "L3 5DA"
head = "Colin Sauze"
email = "colin.sauze@noc.ac.uk"
website = "https://noc.ac.uk"

[nocs]
name = "National Oceanography Centre - Southampton"
lat = 50.8930079
lon = -1.3951406
postcode = "SO14 3ZH"
head = "Colin Sauze"
email = "colin.sauze@noc.ac.uk"
website = "https://noc.ac.uk"

[dundee]
name = "University of Dundee"
head = "Kenny Gillen"
website = "https://www.dundee.ac.uk/it"
email = "k.h.gillen@dundee.ac.uk"
postcode = "DD1 4HN"
lat = 56.456478
lon = -3.011300

[hutton]
name = "The James Hutton Institute"
head = "Iain Milne"
website = "https://ics.hutton.ac.uk/"
email = "iain.milne@hutton.ac.uk"
phone = "01382 568843"
postcode = "DD2 5DA"
lat = 56.457588
lon = -3.062470

[liverpool]
name = "University of Liverpool"
head = "Ian Smith"
website = "https://www.liverpool.ac.uk/it/advanced-research-computing/"
email = "rse-support@liverpool.ac.uk"
postcode = "L69 7ZX"
lat = 53.405865
lon = -2.966894

[warwick]
name = "University of Warwick"
website = "https://warwick.ac.uk/research/rtp/rc/rse/"
postcode = "CV4 7AL"
lat = 52.373734
lon = -1.5523447
email = "resource.rse@warwick.ac.uk"

[eth-sis]
name = "Scientific IT Services of ETH Zurich"
head = "Bernd Rinn"
website = "https://sis.id.ethz.ch"
email = "sis.helpdesk@ethz.ch"
lat = 47.4139693230361
lon = 8.537222400000356
